# Generated by Django 6.0.6 on 2026-06-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_cashaccount_user_account'),
        ('transactions', '0004_alter_transaction_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashAccount',
        ),
    ]
