# Generated by Django 5.1.4 on 2026-06-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_cashaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='color',
            field=models.CharField(blank=True, default='green', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='icon',
            field=models.CharField(blank=True, default='account_balance', max_length=50),
        ),
    ]
