"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
import dj_database_url

# Load environment variables from .env file
load_dotenv()


def env_flag(name, default='False'):
    """Read a boolean env var. Anything but true/1/t (case-insensitive) is False."""
    return os.getenv(name, default).lower() in ('true', '1', 't')


def env_list(name, default=''):
    """Read a comma-separated env var into a list of non-empty, stripped values."""
    return [item.strip() for item in os.getenv(name, default).split(',') if item.strip()]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Every security-sensitive setting below defaults to its SAFE value, so a missing
# env var breaks the deploy instead of silently exposing it. Dev mode is opted
# into (see .env.example / docker-compose.yml), never out of.

# SECURITY WARNING: keep the secret key used in production secret!
# No fallback by design: the previous hardcoded default is public in git history,
# so any fallback here is equivalent to having no secret at all.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured(
        'SECRET_KEY is not set. Generate one with: '
        'python -c "import secrets; print(secrets.token_urlsafe(50))"'
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_flag('DEBUG', 'False')

# Comma-separated list, e.g. "finsight.example.com,www.finsight.example.com".
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'corsheaders',
    'rest_framework',

    # Local apps
    'accounts.apps.AccountsConfig',
    'transactions.apps.TransactionsConfig',
    'reconciliation.apps.ReconciliationConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves collected static files (Django admin's CSS) directly from
    # the app process, so no separate web server is needed. Must sit immediately
    # after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # CORS middleware must be placed before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

db_url = os.getenv('DATABASE_URL')
db_host = os.getenv('DB_HOST')

if db_url:
    DATABASES = {
        'default': dj_database_url.config(
            default=db_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif db_host:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'postgres'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': db_host,
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS configuration
CORS_ALLOW_ALL_ORIGINS = env_flag('CORS_ALLOW_ALL_ORIGINS')
CORS_ALLOWED_ORIGINS = env_list('CORS_ALLOWED_ORIGINS')

# Origins trusted for CSRF-protected (cookie-based) POSTs — in practice only the
# Django admin, since the API authenticates with Bearer JWTs and never uses
# session cookies. Behind an HTTPS proxy (e.g. https://<space>.hf.space) the
# admin login form fails CSRF validation unless its origin is listed here.
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')

# Clerk JWT configuration
CLERK_JWKS_URL = os.getenv('CLERK_JWKS_URL', '')

# Expected 'iss' claim (e.g. https://your-app.clerk.accounts.dev). When set,
# the issuer is verified on every token; leave blank to skip issuer checks.
CLERK_ISSUER = os.getenv('CLERK_ISSUER', '')

# Allow-list for the 'azp' (authorized party) claim - typically your frontend
# origin(s), comma-separated (e.g. http://localhost:3000,https://app.example.com).
# When set, a token whose azp is not in this list is rejected.
CLERK_AUTHORIZED_PARTIES = env_list('CLERK_AUTHORIZED_PARTIES')

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.ClerkJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Production hardening. A misconfigured production deploy should refuse to boot
# rather than serve every request unauthenticated or over plaintext.
if not DEBUG:
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            'ALLOWED_HOSTS must be set when DEBUG=False (comma-separated hostnames).'
        )
    if not CLERK_JWKS_URL:
        raise ImproperlyConfigured(
            'CLERK_JWKS_URL must be set when DEBUG=False, otherwise every '
            'authenticated request fails at runtime.'
        )
    if CORS_ALLOW_ALL_ORIGINS:
        raise ImproperlyConfigured(
            'CORS_ALLOW_ALL_ORIGINS must not be enabled when DEBUG=False. '
            'List your frontend origins in CORS_ALLOWED_ORIGINS instead.'
        )

    # TLS is terminated at the platform proxy (Render/Fly/Vercel), so Django must
    # trust X-Forwarded-Proto to know a request already arrived over HTTPS.
    # Without this, SECURE_SSL_REDIRECT would redirect forever.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# Logging: stream to stdout so the platform's log drain collects it. Without this
# the logger in accounts/authentication.py has nowhere to write, making auth
# failures and JWKS outages invisible in production.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

