# Generated by Django 6.0.6 on 2026-06-25 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
        ('transactions', '0004_alter_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='entry_type',
            field=models.CharField(choices=[('exact', 'Exact'), ('estimated', 'Estimated')], default='exact', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_adjustment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_backdated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reconciliation_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='reconciliation.reconciliationsession'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reconciliation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('adjusted', 'Adjusted')], default='pending', max_length=10),
        ),
    ]
