# Generated by Django 5.1.4 on 2026-06-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_entry_type_transaction_is_adjustment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='entry_type',
            field=models.CharField(choices=[('exact', 'Exact'), ('estimated', 'Estimated'), ('manual', 'Manual')], default='exact', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reconciliation_status',
            field=models.CharField(choices=[('unreconciled', 'Unreconciled'), ('reconciled', 'Reconciled'), ('excluded', 'Excluded')], default='unreconciled', max_length=20),
        ),
    ]
